name: Check versions

on:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * TUE'

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout
        
      - name: versions
        run: |
          staphb_containers=($(grep container configs/cecret_config_template.config | grep staphb | sort | uniq | grep -v latest | awk '{print $3}' | sed 's/'\''//g'))
          for container in ${staphb_containers[@]}
          do
            base=$(echo $container | cut -f 1 -d ":")
            cecret_version=$(echo $container | cut -f 2 -d ":")
            
            docker pull $base:latest
            latest_version=$(docker inspect --format '{{ index .Config.Labels "software.version"}}' $base:latest)
            
            if [[ "$latest_version" == "$cecret_version" ]]
            then
              echo "No version change for $base:$cecret_version" | tee -a versions.txt
            else
              echo "New version for $base! Upgrade to $latest_version from $cecret_version." | tee -a versions.txt
            fi
          done
          issue_text="$(cat versions.txt)"
          echo 'ISSUE_TEXT='$issue_text >> $GITHUB_ENV
          
      - name: Create Issue
        run: |
          gh issue create --title "Version check" --body "$ISSUE_TEXT" --repo $GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
