name: Check versions

on:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * TUE'

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout
        
      - name: versions
        run: |
          staphb_containers=($(grep container configs/cecret_config_template.config | grep staphb | grep -v latest | awk '{print $3}' | sed 's/\'//g'))
          for container in ${staphb_containers[@]}
          do
            echo $container
            base=$(echo $container | cut -f 1 -d ":")
            version=$(echo $container | cut -f 2 -d ":")
            echo "version is $version"
            echo "base is $base"
          done
